---
- name: configure the redis master server
  include_role:
    name: davidwittman.redis
  when: not redis_slave == "true"

- name: configure the redis slave server
  vars:
    - redis_slaveof: "{{ redis_master_hostname }} {{ redis_port }}"
  include_role:
    name: davidwittman.redis
  when: redis_slave == "true"

